#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 154
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 75
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum {
  sym_identifier = 1,
  aux_sym_markdown_token1 = 2,
  sym_tag_start = 3,
  sym_tag_end = 4,
  anon_sym_SLASH = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  anon_sym_POUND = 8,
  sym_null = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  sym_number = 12,
  anon_sym_DQUOTE = 13,
  sym__string_character = 14,
  sym__string_escape_sequence = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  anon_sym_COMMA = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_COLON = 21,
  anon_sym_DOLLAR = 22,
  anon_sym_AT = 23,
  anon_sym_LPAREN = 24,
  anon_sym_RPAREN = 25,
  anon_sym_TAB = 26,
  anon_sym_ = 27,
  anon_sym_LF = 28,
  sym_content = 29,
  sym_markdown = 30,
  sym_tag = 31,
  sym_tag_interior = 32,
  sym_tag_open = 33,
  sym_tag_self_closing = 34,
  sym_tag_close = 35,
  sym_attribute = 36,
  sym__attribute_full = 37,
  sym__attribute_shorthand = 38,
  sym__shorthand_sigil = 39,
  sym_annotation = 40,
  sym_interpolation = 41,
  sym_value = 42,
  sym_primitive = 43,
  sym_boolean = 44,
  sym_string = 45,
  sym__string_element = 46,
  sym_compound = 47,
  sym_array = 48,
  sym__array_item = 49,
  sym__array_item_with_optional_comma = 50,
  sym_hash = 51,
  sym__hash_item = 52,
  sym__hash_key_value = 53,
  sym__hash_item_with_optional_comma = 54,
  sym_hash_key = 55,
  sym_variable = 56,
  sym_variable_tail = 57,
  sym_variable_segment_value = 58,
  sym_variable_sigil = 59,
  sym_function = 60,
  sym_function_parameters = 61,
  sym_function_parameter_tail = 62,
  sym_function_parameter = 63,
  sym_function_parameter_named = 64,
  aux_sym__space = 65,
  aux_sym_content_repeat1 = 66,
  aux_sym_tag_open_repeat1 = 67,
  aux_sym_annotation_repeat1 = 68,
  aux_sym_string_repeat1 = 69,
  aux_sym_array_repeat1 = 70,
  aux_sym_hash_repeat1 = 71,
  aux_sym_variable_repeat1 = 72,
  aux_sym_function_repeat1 = 73,
  aux_sym_function_parameters_repeat1 = 74,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_markdown_token1] = "markdown_token1",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [sym_null] = "null",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_character] = "_string_character",
  [sym__string_escape_sequence] = "_string_escape_sequence",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_TAB] = "\t",
  [anon_sym_] = " ",
  [anon_sym_LF] = "\n",
  [sym_content] = "content",
  [sym_markdown] = "markdown",
  [sym_tag] = "tag",
  [sym_tag_interior] = "tag_interior",
  [sym_tag_open] = "tag_open",
  [sym_tag_self_closing] = "tag_self_closing",
  [sym_tag_close] = "tag_close",
  [sym_attribute] = "attribute",
  [sym__attribute_full] = "_attribute_full",
  [sym__attribute_shorthand] = "_attribute_shorthand",
  [sym__shorthand_sigil] = "_shorthand_sigil",
  [sym_annotation] = "annotation",
  [sym_interpolation] = "interpolation",
  [sym_value] = "value",
  [sym_primitive] = "primitive",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym__string_element] = "_string_element",
  [sym_compound] = "compound",
  [sym_array] = "array",
  [sym__array_item] = "_array_item",
  [sym__array_item_with_optional_comma] = "_array_item_with_optional_comma",
  [sym_hash] = "hash",
  [sym__hash_item] = "_hash_item",
  [sym__hash_key_value] = "_hash_key_value",
  [sym__hash_item_with_optional_comma] = "_hash_item_with_optional_comma",
  [sym_hash_key] = "hash_key",
  [sym_variable] = "variable",
  [sym_variable_tail] = "variable_tail",
  [sym_variable_segment_value] = "variable_segment_value",
  [sym_variable_sigil] = "variable_sigil",
  [sym_function] = "function",
  [sym_function_parameters] = "function_parameters",
  [sym_function_parameter_tail] = "function_parameter_tail",
  [sym_function_parameter] = "function_parameter",
  [sym_function_parameter_named] = "function_parameter_named",
  [aux_sym__space] = "_space",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_tag_open_repeat1] = "tag_open_repeat1",
  [aux_sym_annotation_repeat1] = "annotation_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_hash_repeat1] = "hash_repeat1",
  [aux_sym_variable_repeat1] = "variable_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_function_parameters_repeat1] = "function_parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_markdown_token1] = aux_sym_markdown_token1,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_null] = sym_null,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_character] = sym__string_character,
  [sym__string_escape_sequence] = sym__string_escape_sequence,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_] = anon_sym_,
  [anon_sym_LF] = anon_sym_LF,
  [sym_content] = sym_content,
  [sym_markdown] = sym_markdown,
  [sym_tag] = sym_tag,
  [sym_tag_interior] = sym_tag_interior,
  [sym_tag_open] = sym_tag_open,
  [sym_tag_self_closing] = sym_tag_self_closing,
  [sym_tag_close] = sym_tag_close,
  [sym_attribute] = sym_attribute,
  [sym__attribute_full] = sym__attribute_full,
  [sym__attribute_shorthand] = sym__attribute_shorthand,
  [sym__shorthand_sigil] = sym__shorthand_sigil,
  [sym_annotation] = sym_annotation,
  [sym_interpolation] = sym_interpolation,
  [sym_value] = sym_value,
  [sym_primitive] = sym_primitive,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym__string_element] = sym__string_element,
  [sym_compound] = sym_compound,
  [sym_array] = sym_array,
  [sym__array_item] = sym__array_item,
  [sym__array_item_with_optional_comma] = sym__array_item_with_optional_comma,
  [sym_hash] = sym_hash,
  [sym__hash_item] = sym__hash_item,
  [sym__hash_key_value] = sym__hash_key_value,
  [sym__hash_item_with_optional_comma] = sym__hash_item_with_optional_comma,
  [sym_hash_key] = sym_hash_key,
  [sym_variable] = sym_variable,
  [sym_variable_tail] = sym_variable_tail,
  [sym_variable_segment_value] = sym_variable_segment_value,
  [sym_variable_sigil] = sym_variable_sigil,
  [sym_function] = sym_function,
  [sym_function_parameters] = sym_function_parameters,
  [sym_function_parameter_tail] = sym_function_parameter_tail,
  [sym_function_parameter] = sym_function_parameter,
  [sym_function_parameter_named] = sym_function_parameter_named,
  [aux_sym__space] = aux_sym__space,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_tag_open_repeat1] = aux_sym_tag_open_repeat1,
  [aux_sym_annotation_repeat1] = aux_sym_annotation_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_hash_repeat1] = aux_sym_hash_repeat1,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_function_parameters_repeat1] = aux_sym_function_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markdown_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_character] = {
    .visible = false,
    .named = true,
  },
  [sym__string_escape_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_interior] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_self_closing] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_full] = {
    .visible = false,
    .named = true,
  },
  [sym__attribute_shorthand] = {
    .visible = false,
    .named = true,
  },
  [sym__shorthand_sigil] = {
    .visible = false,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_element] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__array_item] = {
    .visible = false,
    .named = true,
  },
  [sym__array_item_with_optional_comma] = {
    .visible = false,
    .named = true,
  },
  [sym_hash] = {
    .visible = true,
    .named = true,
  },
  [sym__hash_item] = {
    .visible = false,
    .named = true,
  },
  [sym__hash_key_value] = {
    .visible = false,
    .named = true,
  },
  [sym__hash_item_with_optional_comma] = {
    .visible = false,
    .named = true,
  },
  [sym_hash_key] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_segment_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameter_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameter_named] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__space] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_open_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hash_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_tag_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_tag_name] = "tag_name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 4},
  [7] = {.index = 12, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tag_name, 0},
  [1] =
    {field_key, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_tag_name, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_key, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [8] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [12] =
    {field_key, 1, .inherited = true},
    {field_key, 2, .inherited = true},
    {field_value, 1, .inherited = true},
    {field_value, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 3,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 7,
  [12] = 9,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 20,
  [54] = 54,
  [55] = 55,
  [56] = 22,
  [57] = 21,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 25,
  [62] = 58,
  [63] = 23,
  [64] = 60,
  [65] = 32,
  [66] = 30,
  [67] = 37,
  [68] = 68,
  [69] = 69,
  [70] = 42,
  [71] = 71,
  [72] = 26,
  [73] = 73,
  [74] = 31,
  [75] = 38,
  [76] = 34,
  [77] = 77,
  [78] = 39,
  [79] = 41,
  [80] = 29,
  [81] = 81,
  [82] = 24,
  [83] = 27,
  [84] = 84,
  [85] = 77,
  [86] = 36,
  [87] = 33,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 97,
  [104] = 102,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 123,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 137,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 136,
  [143] = 143,
  [144] = 125,
  [145] = 145,
  [146] = 132,
  [147] = 147,
  [148] = 138,
  [149] = 149,
  [150] = 149,
  [151] = 145,
  [152] = 143,
  [153] = 153,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') SKIP(1)
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '{') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(23);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_markdown_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_tag_start);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_tag_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__string_character);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__string_escape_sequence);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '%') ADVANCE(13);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 2},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 2},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 1},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 10},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 10},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 3},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 10},
  [106] = {.lex_state = 10},
  [107] = {.lex_state = 10},
  [108] = {.lex_state = 10},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 10},
  [111] = {.lex_state = 10},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 10},
  [114] = {.lex_state = 10},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 10},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_tag_start] = ACTIONS(1),
    [sym_tag_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__string_escape_sequence] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_content] = STATE(147),
    [sym_markdown] = STATE(84),
    [sym_tag] = STATE(84),
    [sym_annotation] = STATE(84),
    [sym_interpolation] = STATE(84),
    [aux_sym_content_repeat1] = STATE(84),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_markdown_token1] = ACTIONS(5),
    [sym_tag_start] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    STATE(19), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(92), 1,
      sym_value,
    STATE(93), 1,
      sym_attribute,
    STATE(128), 1,
      sym_variable_sigil,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(11), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(15), 2,
      sym_null,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(74), 2,
      sym_boolean,
      sym_string,
    STATE(78), 2,
      sym_array,
      sym_hash,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
    STATE(83), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [73] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(118), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(151), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(10), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [130] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    STATE(118), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(132), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(6), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [187] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(118), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(146), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(3), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [244] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(118), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(145), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(10), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [301] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(12), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [355] = 15,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_null,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(61), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(76), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(8), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [409] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(8), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [463] = 15,
    ACTIONS(83), 1,
      sym_identifier,
    ACTIONS(86), 1,
      sym_null,
    ACTIONS(92), 1,
      sym_number,
    ACTIONS(95), 1,
      anon_sym_DQUOTE,
    ACTIONS(98), 1,
      anon_sym_LBRACK,
    ACTIONS(101), 1,
      anon_sym_RBRACK,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(129), 1,
      sym_value,
    ACTIONS(89), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(106), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(10), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [517] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(109), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(9), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [571] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(111), 1,
      anon_sym_RPAREN,
    STATE(28), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(8), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [625] = 14,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(49), 1,
      sym_function_parameter,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(48), 2,
      sym_value,
      sym_function_parameter_named,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [676] = 15,
    ACTIONS(115), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    STATE(19), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(120), 1,
      sym_tag_open,
    STATE(127), 1,
      sym_tag_interior,
    STATE(128), 1,
      sym_variable_sigil,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(47), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    STATE(99), 2,
      sym_variable,
      sym_function,
    STATE(133), 2,
      sym_tag_self_closing,
      sym_tag_close,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [729] = 15,
    ACTIONS(115), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    STATE(14), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(120), 1,
      sym_tag_open,
    STATE(128), 1,
      sym_variable_sigil,
    STATE(130), 1,
      sym__shorthand_sigil,
    STATE(135), 1,
      sym_tag_interior,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(43), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    STATE(94), 2,
      sym_variable,
      sym_function,
    STATE(133), 2,
      sym_tag_self_closing,
      sym_tag_close,
    ACTIONS(119), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [782] = 13,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(121), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [829] = 13,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(51), 1,
      sym_value,
    STATE(123), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(31), 2,
      sym_boolean,
      sym_string,
    STATE(39), 2,
      sym_array,
      sym_hash,
    STATE(27), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [876] = 13,
    ACTIONS(15), 1,
      sym_null,
    ACTIONS(121), 1,
      sym_identifier,
    ACTIONS(123), 1,
      sym_number,
    ACTIONS(125), 1,
      anon_sym_DQUOTE,
    ACTIONS(127), 1,
      anon_sym_LBRACK,
    ACTIONS(129), 1,
      anon_sym_LBRACE,
    STATE(88), 1,
      sym_value,
    STATE(128), 1,
      sym_variable_sigil,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(74), 2,
      sym_boolean,
      sym_string,
    STATE(78), 2,
      sym_array,
      sym_hash,
    STATE(83), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [923] = 3,
    STATE(19), 1,
      aux_sym__space,
    ACTIONS(133), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
    ACTIONS(131), 14,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      sym_identifier,
  [948] = 5,
    ACTIONS(138), 1,
      anon_sym_DOT,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    STATE(20), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(136), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(141), 9,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [976] = 5,
    ACTIONS(148), 1,
      anon_sym_DOT,
    ACTIONS(152), 1,
      anon_sym_LBRACK,
    STATE(20), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(146), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(150), 9,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1004] = 5,
    ACTIONS(148), 1,
      anon_sym_DOT,
    ACTIONS(152), 1,
      anon_sym_LBRACK,
    STATE(21), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(154), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(156), 9,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1032] = 2,
    ACTIONS(158), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(160), 11,
      anon_sym_DOT,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1052] = 2,
    ACTIONS(162), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(164), 11,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1072] = 2,
    ACTIONS(166), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(168), 11,
      anon_sym_DOT,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1092] = 2,
    ACTIONS(170), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(172), 11,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1112] = 2,
    ACTIONS(174), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(176), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1131] = 4,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    STATE(35), 2,
      sym_function_parameter_tail,
      aux_sym_function_parameters_repeat1,
    ACTIONS(178), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(180), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1154] = 2,
    ACTIONS(184), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(186), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1173] = 2,
    ACTIONS(188), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(190), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1192] = 2,
    ACTIONS(192), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(194), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1211] = 2,
    ACTIONS(196), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(198), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1230] = 2,
    ACTIONS(200), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(202), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1249] = 2,
    ACTIONS(204), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(206), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1268] = 4,
    ACTIONS(182), 1,
      anon_sym_COMMA,
    STATE(40), 2,
      sym_function_parameter_tail,
      aux_sym_function_parameters_repeat1,
    ACTIONS(208), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(210), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1291] = 2,
    ACTIONS(204), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(206), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1310] = 2,
    ACTIONS(212), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(214), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1329] = 2,
    ACTIONS(216), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(218), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1348] = 2,
    ACTIONS(220), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(222), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1367] = 4,
    ACTIONS(228), 1,
      anon_sym_COMMA,
    STATE(40), 2,
      sym_function_parameter_tail,
      aux_sym_function_parameters_repeat1,
    ACTIONS(224), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(226), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1390] = 2,
    ACTIONS(231), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(233), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1409] = 2,
    ACTIONS(235), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(237), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1428] = 9,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(241), 1,
      sym_tag_end,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(98), 1,
      aux_sym__space,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(50), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    ACTIONS(243), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1460] = 9,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(93), 1,
      sym_attribute,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(245), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1492] = 9,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(93), 1,
      sym_attribute,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(247), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1524] = 9,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(93), 1,
      sym_attribute,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(249), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1556] = 9,
    ACTIONS(239), 1,
      sym_identifier,
    ACTIONS(251), 1,
      sym_tag_end,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(101), 1,
      aux_sym__space,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(50), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    ACTIONS(253), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1588] = 2,
    ACTIONS(255), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(257), 8,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1605] = 2,
    ACTIONS(259), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(261), 8,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1622] = 7,
    ACTIONS(263), 1,
      sym_identifier,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(268), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(50), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    ACTIONS(266), 4,
      sym_tag_end,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1649] = 2,
    ACTIONS(271), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(273), 8,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1666] = 2,
    ACTIONS(275), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(277), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
  [1682] = 4,
    ACTIONS(279), 1,
      anon_sym_DOT,
    ACTIONS(282), 1,
      anon_sym_LBRACK,
    STATE(53), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(136), 7,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1702] = 8,
    ACTIONS(239), 1,
      sym_identifier,
    STATE(19), 1,
      aux_sym__space,
    STATE(68), 1,
      sym__attribute_full,
    STATE(69), 1,
      sym__attribute_shorthand,
    STATE(93), 1,
      sym_attribute,
    STATE(130), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1730] = 2,
    ACTIONS(275), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(277), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
  [1746] = 4,
    ACTIONS(285), 1,
      anon_sym_DOT,
    ACTIONS(287), 1,
      anon_sym_LBRACK,
    STATE(57), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(154), 7,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1766] = 4,
    ACTIONS(285), 1,
      anon_sym_DOT,
    ACTIONS(287), 1,
      anon_sym_LBRACK,
    STATE(53), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(146), 7,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1786] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(289), 1,
      sym_identifier,
    ACTIONS(291), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_hash_repeat1,
    STATE(109), 1,
      sym__hash_item,
    STATE(117), 1,
      sym__hash_key_value,
    STATE(131), 1,
      sym_string,
    STATE(141), 1,
      sym_hash_key,
    STATE(143), 1,
      sym__hash_item_with_optional_comma,
  [1814] = 6,
    ACTIONS(295), 1,
      anon_sym_EQ,
    ACTIONS(297), 1,
      anon_sym_LPAREN,
    STATE(2), 1,
      aux_sym__space,
    STATE(89), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(293), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(299), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1836] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(289), 1,
      sym_identifier,
    ACTIONS(301), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      aux_sym_hash_repeat1,
    STATE(109), 1,
      sym__hash_item,
    STATE(117), 1,
      sym__hash_key_value,
    STATE(131), 1,
      sym_string,
    STATE(138), 1,
      sym__hash_item_with_optional_comma,
    STATE(141), 1,
      sym_hash_key,
  [1864] = 1,
    ACTIONS(166), 9,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LBRACK,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1876] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(289), 1,
      sym_identifier,
    ACTIONS(303), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_hash_repeat1,
    STATE(109), 1,
      sym__hash_item,
    STATE(117), 1,
      sym__hash_key_value,
    STATE(131), 1,
      sym_string,
    STATE(141), 1,
      sym_hash_key,
    STATE(152), 1,
      sym__hash_item_with_optional_comma,
  [1904] = 1,
    ACTIONS(158), 9,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LBRACK,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1916] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(289), 1,
      sym_identifier,
    ACTIONS(305), 1,
      anon_sym_RBRACE,
    STATE(62), 1,
      aux_sym_hash_repeat1,
    STATE(109), 1,
      sym__hash_item,
    STATE(117), 1,
      sym__hash_key_value,
    STATE(131), 1,
      sym_string,
    STATE(141), 1,
      sym_hash_key,
    STATE(148), 1,
      sym__hash_item_with_optional_comma,
  [1944] = 1,
    ACTIONS(196), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1955] = 1,
    ACTIONS(188), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1966] = 1,
    ACTIONS(212), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1977] = 1,
    ACTIONS(307), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1988] = 1,
    ACTIONS(309), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1999] = 1,
    ACTIONS(235), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2010] = 4,
    ACTIONS(311), 1,
      ts_builtin_sym_end,
    ACTIONS(313), 1,
      aux_sym_markdown_token1,
    ACTIONS(316), 1,
      sym_tag_start,
    STATE(71), 5,
      sym_markdown,
      sym_tag,
      sym_annotation,
      sym_interpolation,
      aux_sym_content_repeat1,
  [2027] = 1,
    ACTIONS(170), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2038] = 1,
    ACTIONS(319), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2049] = 1,
    ACTIONS(192), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2060] = 1,
    ACTIONS(216), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2071] = 1,
    ACTIONS(204), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2082] = 6,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(321), 1,
      sym_number,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(149), 1,
      sym_variable_segment_value,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(137), 2,
      sym_string,
      sym_variable,
  [2103] = 1,
    ACTIONS(220), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2114] = 1,
    ACTIONS(231), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2125] = 1,
    ACTIONS(184), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2136] = 8,
    ACTIONS(323), 1,
      sym_identifier,
    ACTIONS(326), 1,
      anon_sym_DQUOTE,
    ACTIONS(329), 1,
      anon_sym_RBRACE,
    STATE(81), 1,
      aux_sym_hash_repeat1,
    STATE(109), 1,
      sym__hash_item,
    STATE(131), 1,
      sym_string,
    STATE(139), 1,
      sym__hash_key_value,
    STATE(141), 1,
      sym_hash_key,
  [2161] = 1,
    ACTIONS(162), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2172] = 1,
    ACTIONS(174), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2183] = 4,
    ACTIONS(5), 1,
      aux_sym_markdown_token1,
    ACTIONS(7), 1,
      sym_tag_start,
    ACTIONS(331), 1,
      ts_builtin_sym_end,
    STATE(71), 5,
      sym_markdown,
      sym_tag,
      sym_annotation,
      sym_interpolation,
      aux_sym_content_repeat1,
  [2200] = 6,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(321), 1,
      sym_number,
    STATE(123), 1,
      sym_variable_sigil,
    STATE(150), 1,
      sym_variable_segment_value,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(137), 2,
      sym_string,
      sym_variable,
  [2221] = 1,
    ACTIONS(204), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2232] = 1,
    ACTIONS(200), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2243] = 1,
    ACTIONS(333), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2254] = 4,
    STATE(46), 1,
      aux_sym__space,
    STATE(90), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(11), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(335), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2270] = 4,
    STATE(54), 1,
      aux_sym__space,
    STATE(90), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(337), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(339), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2286] = 4,
    STATE(44), 1,
      aux_sym__space,
    STATE(90), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(247), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(342), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2302] = 4,
    STATE(45), 1,
      aux_sym__space,
    STATE(91), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(249), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(344), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2318] = 1,
    ACTIONS(337), 5,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2326] = 3,
    ACTIONS(346), 1,
      sym_tag_end,
    STATE(96), 1,
      aux_sym__space,
    ACTIONS(348), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2338] = 3,
    ACTIONS(350), 1,
      sym_tag_end,
    STATE(19), 1,
      aux_sym__space,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2350] = 3,
    ACTIONS(352), 1,
      sym_tag_end,
    STATE(19), 1,
      aux_sym__space,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2362] = 3,
    ACTIONS(354), 1,
      anon_sym_DQUOTE,
    ACTIONS(356), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(100), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2374] = 3,
    ACTIONS(251), 1,
      sym_tag_end,
    STATE(19), 1,
      aux_sym__space,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2386] = 3,
    ACTIONS(352), 1,
      sym_tag_end,
    STATE(95), 1,
      aux_sym__space,
    ACTIONS(358), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2398] = 3,
    ACTIONS(360), 1,
      anon_sym_DQUOTE,
    ACTIONS(362), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(100), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2410] = 3,
    ACTIONS(365), 1,
      sym_tag_end,
    STATE(19), 1,
      aux_sym__space,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2422] = 3,
    ACTIONS(367), 1,
      anon_sym_DQUOTE,
    ACTIONS(369), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(103), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2434] = 3,
    ACTIONS(371), 1,
      anon_sym_DQUOTE,
    ACTIONS(356), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(100), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2446] = 3,
    ACTIONS(373), 1,
      anon_sym_DQUOTE,
    ACTIONS(375), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(97), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2458] = 1,
    ACTIONS(377), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2464] = 1,
    ACTIONS(379), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2470] = 1,
    ACTIONS(381), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2476] = 1,
    ACTIONS(383), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2482] = 1,
    ACTIONS(385), 3,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
  [2488] = 1,
    ACTIONS(387), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2494] = 1,
    ACTIONS(389), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2500] = 1,
    ACTIONS(391), 3,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
  [2506] = 1,
    ACTIONS(393), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2512] = 1,
    ACTIONS(395), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2518] = 1,
    ACTIONS(391), 3,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
  [2524] = 1,
    ACTIONS(397), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2530] = 2,
    ACTIONS(399), 1,
      anon_sym_COMMA,
    ACTIONS(401), 1,
      anon_sym_RBRACE,
  [2537] = 2,
    ACTIONS(403), 1,
      anon_sym_RBRACK,
    ACTIONS(405), 1,
      anon_sym_COMMA,
  [2544] = 2,
    ACTIONS(407), 1,
      anon_sym_EQ,
    ACTIONS(409), 1,
      anon_sym_LPAREN,
  [2551] = 2,
    ACTIONS(411), 1,
      sym_tag_end,
    ACTIONS(413), 1,
      anon_sym_SLASH,
  [2558] = 1,
    ACTIONS(415), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2563] = 2,
    ACTIONS(417), 1,
      anon_sym_EQ,
    ACTIONS(419), 1,
      anon_sym_LPAREN,
  [2570] = 1,
    ACTIONS(421), 1,
      sym_identifier,
  [2574] = 1,
    ACTIONS(417), 1,
      anon_sym_EQ,
  [2578] = 1,
    ACTIONS(423), 1,
      sym_identifier,
  [2582] = 1,
    ACTIONS(425), 1,
      sym_tag_end,
  [2586] = 1,
    ACTIONS(427), 1,
      sym_tag_end,
  [2590] = 1,
    ACTIONS(429), 1,
      sym_identifier,
  [2594] = 1,
    ACTIONS(431), 1,
      anon_sym_COMMA,
  [2598] = 1,
    ACTIONS(433), 1,
      sym_identifier,
  [2602] = 1,
    ACTIONS(435), 1,
      anon_sym_COLON,
  [2606] = 1,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
  [2610] = 1,
    ACTIONS(411), 1,
      sym_tag_end,
  [2614] = 1,
    ACTIONS(437), 1,
      sym_identifier,
  [2618] = 1,
    ACTIONS(439), 1,
      sym_tag_end,
  [2622] = 1,
    ACTIONS(419), 1,
      anon_sym_LPAREN,
  [2626] = 1,
    ACTIONS(441), 1,
      anon_sym_RBRACK,
  [2630] = 1,
    ACTIONS(443), 1,
      anon_sym_RBRACE,
  [2634] = 1,
    ACTIONS(445), 1,
      anon_sym_COMMA,
  [2638] = 1,
    ACTIONS(447), 1,
      sym_identifier,
  [2642] = 1,
    ACTIONS(449), 1,
      anon_sym_COLON,
  [2646] = 1,
    ACTIONS(409), 1,
      anon_sym_LPAREN,
  [2650] = 1,
    ACTIONS(451), 1,
      anon_sym_RBRACE,
  [2654] = 1,
    ACTIONS(453), 1,
      sym_identifier,
  [2658] = 1,
    ACTIONS(455), 1,
      anon_sym_RBRACK,
  [2662] = 1,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
  [2666] = 1,
    ACTIONS(457), 1,
      ts_builtin_sym_end,
  [2670] = 1,
    ACTIONS(459), 1,
      anon_sym_RBRACE,
  [2674] = 1,
    ACTIONS(461), 1,
      anon_sym_RBRACK,
  [2678] = 1,
    ACTIONS(463), 1,
      anon_sym_RBRACK,
  [2682] = 1,
    ACTIONS(465), 1,
      anon_sym_RBRACK,
  [2686] = 1,
    ACTIONS(467), 1,
      anon_sym_RBRACE,
  [2690] = 1,
    ACTIONS(469), 1,
      sym_tag_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 73,
  [SMALL_STATE(4)] = 130,
  [SMALL_STATE(5)] = 187,
  [SMALL_STATE(6)] = 244,
  [SMALL_STATE(7)] = 301,
  [SMALL_STATE(8)] = 355,
  [SMALL_STATE(9)] = 409,
  [SMALL_STATE(10)] = 463,
  [SMALL_STATE(11)] = 517,
  [SMALL_STATE(12)] = 571,
  [SMALL_STATE(13)] = 625,
  [SMALL_STATE(14)] = 676,
  [SMALL_STATE(15)] = 729,
  [SMALL_STATE(16)] = 782,
  [SMALL_STATE(17)] = 829,
  [SMALL_STATE(18)] = 876,
  [SMALL_STATE(19)] = 923,
  [SMALL_STATE(20)] = 948,
  [SMALL_STATE(21)] = 976,
  [SMALL_STATE(22)] = 1004,
  [SMALL_STATE(23)] = 1032,
  [SMALL_STATE(24)] = 1052,
  [SMALL_STATE(25)] = 1072,
  [SMALL_STATE(26)] = 1092,
  [SMALL_STATE(27)] = 1112,
  [SMALL_STATE(28)] = 1131,
  [SMALL_STATE(29)] = 1154,
  [SMALL_STATE(30)] = 1173,
  [SMALL_STATE(31)] = 1192,
  [SMALL_STATE(32)] = 1211,
  [SMALL_STATE(33)] = 1230,
  [SMALL_STATE(34)] = 1249,
  [SMALL_STATE(35)] = 1268,
  [SMALL_STATE(36)] = 1291,
  [SMALL_STATE(37)] = 1310,
  [SMALL_STATE(38)] = 1329,
  [SMALL_STATE(39)] = 1348,
  [SMALL_STATE(40)] = 1367,
  [SMALL_STATE(41)] = 1390,
  [SMALL_STATE(42)] = 1409,
  [SMALL_STATE(43)] = 1428,
  [SMALL_STATE(44)] = 1460,
  [SMALL_STATE(45)] = 1492,
  [SMALL_STATE(46)] = 1524,
  [SMALL_STATE(47)] = 1556,
  [SMALL_STATE(48)] = 1588,
  [SMALL_STATE(49)] = 1605,
  [SMALL_STATE(50)] = 1622,
  [SMALL_STATE(51)] = 1649,
  [SMALL_STATE(52)] = 1666,
  [SMALL_STATE(53)] = 1682,
  [SMALL_STATE(54)] = 1702,
  [SMALL_STATE(55)] = 1730,
  [SMALL_STATE(56)] = 1746,
  [SMALL_STATE(57)] = 1766,
  [SMALL_STATE(58)] = 1786,
  [SMALL_STATE(59)] = 1814,
  [SMALL_STATE(60)] = 1836,
  [SMALL_STATE(61)] = 1864,
  [SMALL_STATE(62)] = 1876,
  [SMALL_STATE(63)] = 1904,
  [SMALL_STATE(64)] = 1916,
  [SMALL_STATE(65)] = 1944,
  [SMALL_STATE(66)] = 1955,
  [SMALL_STATE(67)] = 1966,
  [SMALL_STATE(68)] = 1977,
  [SMALL_STATE(69)] = 1988,
  [SMALL_STATE(70)] = 1999,
  [SMALL_STATE(71)] = 2010,
  [SMALL_STATE(72)] = 2027,
  [SMALL_STATE(73)] = 2038,
  [SMALL_STATE(74)] = 2049,
  [SMALL_STATE(75)] = 2060,
  [SMALL_STATE(76)] = 2071,
  [SMALL_STATE(77)] = 2082,
  [SMALL_STATE(78)] = 2103,
  [SMALL_STATE(79)] = 2114,
  [SMALL_STATE(80)] = 2125,
  [SMALL_STATE(81)] = 2136,
  [SMALL_STATE(82)] = 2161,
  [SMALL_STATE(83)] = 2172,
  [SMALL_STATE(84)] = 2183,
  [SMALL_STATE(85)] = 2200,
  [SMALL_STATE(86)] = 2221,
  [SMALL_STATE(87)] = 2232,
  [SMALL_STATE(88)] = 2243,
  [SMALL_STATE(89)] = 2254,
  [SMALL_STATE(90)] = 2270,
  [SMALL_STATE(91)] = 2286,
  [SMALL_STATE(92)] = 2302,
  [SMALL_STATE(93)] = 2318,
  [SMALL_STATE(94)] = 2326,
  [SMALL_STATE(95)] = 2338,
  [SMALL_STATE(96)] = 2350,
  [SMALL_STATE(97)] = 2362,
  [SMALL_STATE(98)] = 2374,
  [SMALL_STATE(99)] = 2386,
  [SMALL_STATE(100)] = 2398,
  [SMALL_STATE(101)] = 2410,
  [SMALL_STATE(102)] = 2422,
  [SMALL_STATE(103)] = 2434,
  [SMALL_STATE(104)] = 2446,
  [SMALL_STATE(105)] = 2458,
  [SMALL_STATE(106)] = 2464,
  [SMALL_STATE(107)] = 2470,
  [SMALL_STATE(108)] = 2476,
  [SMALL_STATE(109)] = 2482,
  [SMALL_STATE(110)] = 2488,
  [SMALL_STATE(111)] = 2494,
  [SMALL_STATE(112)] = 2500,
  [SMALL_STATE(113)] = 2506,
  [SMALL_STATE(114)] = 2512,
  [SMALL_STATE(115)] = 2518,
  [SMALL_STATE(116)] = 2524,
  [SMALL_STATE(117)] = 2530,
  [SMALL_STATE(118)] = 2537,
  [SMALL_STATE(119)] = 2544,
  [SMALL_STATE(120)] = 2551,
  [SMALL_STATE(121)] = 2558,
  [SMALL_STATE(122)] = 2563,
  [SMALL_STATE(123)] = 2570,
  [SMALL_STATE(124)] = 2574,
  [SMALL_STATE(125)] = 2578,
  [SMALL_STATE(126)] = 2582,
  [SMALL_STATE(127)] = 2586,
  [SMALL_STATE(128)] = 2590,
  [SMALL_STATE(129)] = 2594,
  [SMALL_STATE(130)] = 2598,
  [SMALL_STATE(131)] = 2602,
  [SMALL_STATE(132)] = 2606,
  [SMALL_STATE(133)] = 2610,
  [SMALL_STATE(134)] = 2614,
  [SMALL_STATE(135)] = 2618,
  [SMALL_STATE(136)] = 2622,
  [SMALL_STATE(137)] = 2626,
  [SMALL_STATE(138)] = 2630,
  [SMALL_STATE(139)] = 2634,
  [SMALL_STATE(140)] = 2638,
  [SMALL_STATE(141)] = 2642,
  [SMALL_STATE(142)] = 2646,
  [SMALL_STATE(143)] = 2650,
  [SMALL_STATE(144)] = 2654,
  [SMALL_STATE(145)] = 2658,
  [SMALL_STATE(146)] = 2662,
  [SMALL_STATE(147)] = 2666,
  [SMALL_STATE(148)] = 2670,
  [SMALL_STATE(149)] = 2674,
  [SMALL_STATE(150)] = 2678,
  [SMALL_STATE(151)] = 2682,
  [SMALL_STATE(152)] = 2686,
  [SMALL_STATE(153)] = 2690,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 2, .production_id = 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(130),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(102),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(134),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(142),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(142),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(31),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(29),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(31),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(104),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(5),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(64),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(134),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [83] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(142),
  [86] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(31),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(29),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(31),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(104),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(64),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(134),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [121] = {.entry = {.count = 1, .reusable = false}}, SHIFT(136),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__space, 2),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__space, 2), SHIFT_REPEAT(19),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(144),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(85),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_tail, 3),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_tail, 3),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_tail, 2),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_tail, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameters, 1),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 1),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 4, .production_id = 7),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 4, .production_id = 7),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 3, .production_id = 5),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 3, .production_id = 5),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameters, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 1),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_parameters_repeat1, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_parameters_repeat1, 2),
  [228] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_parameters_repeat1, 2), SHIFT_REPEAT(13),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 2),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 2),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 5, .production_id = 1),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 4, .production_id = 1),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 3, .production_id = 1),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(106),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameter, 1),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameter, 1),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameter_tail, 2),
  [261] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameter_tail, 2),
  [263] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2), SHIFT_REPEAT(124),
  [266] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2),
  [268] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2), SHIFT_REPEAT(130),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameter_named, 3),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameter_named, 3),
  [275] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__array_item, 2),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_item, 2),
  [279] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(125),
  [282] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(77),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [287] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 1, .production_id = 1),
  [295] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [297] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [299] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, .production_id = 2),
  [309] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2),
  [313] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(111),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(15),
  [319] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__attribute_shorthand, 2),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [323] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, .production_id = 6), SHIFT_REPEAT(131),
  [326] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, .production_id = 6), SHIFT_REPEAT(104),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, .production_id = 6),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1),
  [333] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__attribute_full, 3, .production_id = 4),
  [335] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [337] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_open_repeat1, 2),
  [339] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_open_repeat1, 2), SHIFT_REPEAT(54),
  [342] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [344] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(113),
  [348] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [350] = {.entry = {.count = 1, .reusable = false}}, SHIFT(116),
  [352] = {.entry = {.count = 1, .reusable = false}}, SHIFT(108),
  [354] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [358] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [360] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [362] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(100),
  [365] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [367] = {.entry = {.count = 1, .reusable = false}}, SHIFT(72),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [371] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [373] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [377] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 5),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 4),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 4),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 1, .production_id = 2),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown, 1),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hash_item, 2, .production_id = 2),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 3),
  [397] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 5),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [401] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hash_item_with_optional_comma, 1, .production_id = 2),
  [403] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_item_with_optional_comma, 1),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [411] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_interior, 1),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(153),
  [415] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hash_key_value, 3, .production_id = 4),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [419] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [421] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [423] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [425] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_close, 2, .production_id = 3),
  [427] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [435] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_key, 1),
  [437] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_sigil, 1),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [441] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_segment_value, 1),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [453] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [455] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [457] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [459] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [461] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [463] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [465] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [467] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [469] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_self_closing, 2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_markdoc(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
