#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 154
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 76
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 8

enum {
  sym_identifier = 1,
  aux_sym_markdown_token1 = 2,
  sym_tag_start = 3,
  sym_tag_end = 4,
  anon_sym_SLASH = 5,
  anon_sym_EQ = 6,
  anon_sym_DOT = 7,
  anon_sym_POUND = 8,
  sym_null = 9,
  anon_sym_true = 10,
  anon_sym_false = 11,
  sym_number = 12,
  anon_sym_DQUOTE = 13,
  sym__string_character = 14,
  sym__string_escape_sequence = 15,
  anon_sym_LBRACK = 16,
  anon_sym_RBRACK = 17,
  anon_sym_COMMA = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_COLON = 21,
  anon_sym_DOLLAR = 22,
  anon_sym_AT = 23,
  anon_sym_LPAREN = 24,
  anon_sym_RPAREN = 25,
  anon_sym_TAB = 26,
  anon_sym_ = 27,
  anon_sym_LF = 28,
  sym_content = 29,
  sym_markdown = 30,
  sym_tag = 31,
  sym_tag_interior = 32,
  sym_tag_open = 33,
  sym_tag_self_closing = 34,
  sym_tag_close = 35,
  sym_attribute = 36,
  sym__attribute_full = 37,
  sym__attribute_shorthand = 38,
  sym__shorthand_sigil = 39,
  sym_annotation = 40,
  sym_interpolation = 41,
  sym_value = 42,
  sym_primitive = 43,
  sym_boolean = 44,
  sym_string = 45,
  sym__string_element = 46,
  sym_compound = 47,
  sym_array = 48,
  sym__array_item = 49,
  sym__array_item_with_optional_comma = 50,
  sym_hash = 51,
  sym__hash_item = 52,
  sym__hash_key_value = 53,
  sym__hash_item_with_optional_comma = 54,
  sym_hash_key = 55,
  sym_variable = 56,
  sym_variable_tail = 57,
  sym_variable_segment_value = 58,
  sym_variable_sigil = 59,
  sym_function = 60,
  sym_function_parameters = 61,
  sym_function_parameter_tail = 62,
  sym_function_parameter = 63,
  sym_function_parameter_named = 64,
  aux_sym__space = 65,
  aux_sym_content_repeat1 = 66,
  aux_sym_tag_open_repeat1 = 67,
  aux_sym_annotation_repeat1 = 68,
  aux_sym_interpolation_repeat1 = 69,
  aux_sym_string_repeat1 = 70,
  aux_sym_array_repeat1 = 71,
  aux_sym_hash_repeat1 = 72,
  aux_sym_variable_repeat1 = 73,
  aux_sym_function_repeat1 = 74,
  aux_sym_function_parameters_repeat1 = 75,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_markdown_token1] = "markdown_token1",
  [sym_tag_start] = "tag_start",
  [sym_tag_end] = "tag_end",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [anon_sym_DOT] = ".",
  [anon_sym_POUND] = "#",
  [sym_null] = "null",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_number] = "number",
  [anon_sym_DQUOTE] = "\"",
  [sym__string_character] = "_string_character",
  [sym__string_escape_sequence] = "_string_escape_sequence",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COMMA] = ",",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [anon_sym_DOLLAR] = "$",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_TAB] = "\t",
  [anon_sym_] = " ",
  [anon_sym_LF] = "\n",
  [sym_content] = "content",
  [sym_markdown] = "markdown",
  [sym_tag] = "tag",
  [sym_tag_interior] = "tag_interior",
  [sym_tag_open] = "tag_open",
  [sym_tag_self_closing] = "tag_self_closing",
  [sym_tag_close] = "tag_close",
  [sym_attribute] = "attribute",
  [sym__attribute_full] = "_attribute_full",
  [sym__attribute_shorthand] = "_attribute_shorthand",
  [sym__shorthand_sigil] = "_shorthand_sigil",
  [sym_annotation] = "annotation",
  [sym_interpolation] = "interpolation",
  [sym_value] = "value",
  [sym_primitive] = "primitive",
  [sym_boolean] = "boolean",
  [sym_string] = "string",
  [sym__string_element] = "_string_element",
  [sym_compound] = "compound",
  [sym_array] = "array",
  [sym__array_item] = "_array_item",
  [sym__array_item_with_optional_comma] = "_array_item_with_optional_comma",
  [sym_hash] = "hash",
  [sym__hash_item] = "_hash_item",
  [sym__hash_key_value] = "_hash_key_value",
  [sym__hash_item_with_optional_comma] = "_hash_item_with_optional_comma",
  [sym_hash_key] = "hash_key",
  [sym_variable] = "variable",
  [sym_variable_tail] = "variable_tail",
  [sym_variable_segment_value] = "variable_segment_value",
  [sym_variable_sigil] = "variable_sigil",
  [sym_function] = "function",
  [sym_function_parameters] = "function_parameters",
  [sym_function_parameter_tail] = "function_parameter_tail",
  [sym_function_parameter] = "function_parameter",
  [sym_function_parameter_named] = "function_parameter_named",
  [aux_sym__space] = "_space",
  [aux_sym_content_repeat1] = "content_repeat1",
  [aux_sym_tag_open_repeat1] = "tag_open_repeat1",
  [aux_sym_annotation_repeat1] = "annotation_repeat1",
  [aux_sym_interpolation_repeat1] = "interpolation_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_hash_repeat1] = "hash_repeat1",
  [aux_sym_variable_repeat1] = "variable_repeat1",
  [aux_sym_function_repeat1] = "function_repeat1",
  [aux_sym_function_parameters_repeat1] = "function_parameters_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_markdown_token1] = aux_sym_markdown_token1,
  [sym_tag_start] = sym_tag_start,
  [sym_tag_end] = sym_tag_end,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_POUND] = anon_sym_POUND,
  [sym_null] = sym_null,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_number] = sym_number,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym__string_character] = sym__string_character,
  [sym__string_escape_sequence] = sym__string_escape_sequence,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_DOLLAR] = anon_sym_DOLLAR,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_TAB] = anon_sym_TAB,
  [anon_sym_] = anon_sym_,
  [anon_sym_LF] = anon_sym_LF,
  [sym_content] = sym_content,
  [sym_markdown] = sym_markdown,
  [sym_tag] = sym_tag,
  [sym_tag_interior] = sym_tag_interior,
  [sym_tag_open] = sym_tag_open,
  [sym_tag_self_closing] = sym_tag_self_closing,
  [sym_tag_close] = sym_tag_close,
  [sym_attribute] = sym_attribute,
  [sym__attribute_full] = sym__attribute_full,
  [sym__attribute_shorthand] = sym__attribute_shorthand,
  [sym__shorthand_sigil] = sym__shorthand_sigil,
  [sym_annotation] = sym_annotation,
  [sym_interpolation] = sym_interpolation,
  [sym_value] = sym_value,
  [sym_primitive] = sym_primitive,
  [sym_boolean] = sym_boolean,
  [sym_string] = sym_string,
  [sym__string_element] = sym__string_element,
  [sym_compound] = sym_compound,
  [sym_array] = sym_array,
  [sym__array_item] = sym__array_item,
  [sym__array_item_with_optional_comma] = sym__array_item_with_optional_comma,
  [sym_hash] = sym_hash,
  [sym__hash_item] = sym__hash_item,
  [sym__hash_key_value] = sym__hash_key_value,
  [sym__hash_item_with_optional_comma] = sym__hash_item_with_optional_comma,
  [sym_hash_key] = sym_hash_key,
  [sym_variable] = sym_variable,
  [sym_variable_tail] = sym_variable_tail,
  [sym_variable_segment_value] = sym_variable_segment_value,
  [sym_variable_sigil] = sym_variable_sigil,
  [sym_function] = sym_function,
  [sym_function_parameters] = sym_function_parameters,
  [sym_function_parameter_tail] = sym_function_parameter_tail,
  [sym_function_parameter] = sym_function_parameter,
  [sym_function_parameter_named] = sym_function_parameter_named,
  [aux_sym__space] = aux_sym__space,
  [aux_sym_content_repeat1] = aux_sym_content_repeat1,
  [aux_sym_tag_open_repeat1] = aux_sym_tag_open_repeat1,
  [aux_sym_annotation_repeat1] = aux_sym_annotation_repeat1,
  [aux_sym_interpolation_repeat1] = aux_sym_interpolation_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_hash_repeat1] = aux_sym_hash_repeat1,
  [aux_sym_variable_repeat1] = aux_sym_variable_repeat1,
  [aux_sym_function_repeat1] = aux_sym_function_repeat1,
  [aux_sym_function_parameters_repeat1] = aux_sym_function_parameters_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_markdown_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_tag_start] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_end] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym_null] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym__string_character] = {
    .visible = false,
    .named = true,
  },
  [sym__string_escape_sequence] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOLLAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym_markdown] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_interior] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_open] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_self_closing] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_close] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_full] = {
    .visible = false,
    .named = true,
  },
  [sym__attribute_shorthand] = {
    .visible = false,
    .named = true,
  },
  [sym__shorthand_sigil] = {
    .visible = false,
    .named = true,
  },
  [sym_annotation] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__string_element] = {
    .visible = false,
    .named = true,
  },
  [sym_compound] = {
    .visible = true,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym__array_item] = {
    .visible = false,
    .named = true,
  },
  [sym__array_item_with_optional_comma] = {
    .visible = false,
    .named = true,
  },
  [sym_hash] = {
    .visible = true,
    .named = true,
  },
  [sym__hash_item] = {
    .visible = false,
    .named = true,
  },
  [sym__hash_key_value] = {
    .visible = false,
    .named = true,
  },
  [sym__hash_item_with_optional_comma] = {
    .visible = false,
    .named = true,
  },
  [sym_hash_key] = {
    .visible = true,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_segment_value] = {
    .visible = true,
    .named = true,
  },
  [sym_variable_sigil] = {
    .visible = true,
    .named = true,
  },
  [sym_function] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameters] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameter_tail] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_function_parameter_named] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__space] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_content_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_open_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_annotation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_interpolation_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hash_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_variable_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_parameters_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_tag_name = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_tag_name] = "tag_name",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
  [6] = {.index = 8, .length = 4},
  [7] = {.index = 12, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_tag_name, 0},
  [1] =
    {field_key, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_tag_name, 1},
  [4] =
    {field_key, 0},
    {field_value, 2},
  [6] =
    {field_key, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [8] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [12] =
    {field_key, 1, .inherited = true},
    {field_key, 2, .inherited = true},
    {field_value, 1, .inherited = true},
    {field_value, 2, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 7,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 20,
  [55] = 21,
  [56] = 22,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 23,
  [63] = 25,
  [64] = 64,
  [65] = 61,
  [66] = 66,
  [67] = 64,
  [68] = 42,
  [69] = 69,
  [70] = 40,
  [71] = 71,
  [72] = 72,
  [73] = 30,
  [74] = 29,
  [75] = 75,
  [76] = 26,
  [77] = 31,
  [78] = 78,
  [79] = 79,
  [80] = 72,
  [81] = 81,
  [82] = 24,
  [83] = 83,
  [84] = 84,
  [85] = 28,
  [86] = 27,
  [87] = 33,
  [88] = 32,
  [89] = 39,
  [90] = 38,
  [91] = 35,
  [92] = 36,
  [93] = 93,
  [94] = 94,
  [95] = 95,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 101,
  [103] = 103,
  [104] = 103,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 128,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 135,
  [136] = 136,
  [137] = 135,
  [138] = 138,
  [139] = 139,
  [140] = 140,
  [141] = 141,
  [142] = 142,
  [143] = 132,
  [144] = 144,
  [145] = 142,
  [146] = 146,
  [147] = 147,
  [148] = 127,
  [149] = 149,
  [150] = 139,
  [151] = 130,
  [152] = 124,
  [153] = 149,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == '\r') SKIP(1)
      if (lookahead == ' ') ADVANCE(37);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '{') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(27);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == '}') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't') ADVANCE(23);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 8:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 9:
      if (eof) ADVANCE(11);
      if (lookahead == '"') ADVANCE(21);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '$') ADVANCE(31);
      if (lookahead == '%') ADVANCE(5);
      if (lookahead == '(') ADVANCE(33);
      if (lookahead == ')') ADVANCE(34);
      if (lookahead == ',') ADVANCE(26);
      if (lookahead == '-') ADVANCE(7);
      if (lookahead == '.') ADVANCE(17);
      if (lookahead == '/') ADVANCE(15);
      if (lookahead == ':') ADVANCE(30);
      if (lookahead == '=') ADVANCE(16);
      if (lookahead == '@') ADVANCE(32);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == ']') ADVANCE(25);
      if (lookahead == '{') ADVANCE(28);
      if (lookahead == '}') ADVANCE(29);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(9)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '{') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(10)
      if (lookahead != 0) ADVANCE(12);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_markdown_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_tag_start);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_tag_end);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(8);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym__string_character);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym__string_escape_sequence);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      if (lookahead == '%') ADVANCE(13);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_DOLLAR);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\t') ADVANCE(36);
      if (lookahead == '\n') ADVANCE(38);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'f') ADVANCE(1);
      if (lookahead == 'n') ADVANCE(2);
      if (lookahead == 't') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      END_STATE();
    case 1:
      if (lookahead == 'a') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'u') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'r') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_null);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 2},
  [4] = {.lex_state = 2},
  [5] = {.lex_state = 2},
  [6] = {.lex_state = 2},
  [7] = {.lex_state = 2},
  [8] = {.lex_state = 2},
  [9] = {.lex_state = 2},
  [10] = {.lex_state = 2},
  [11] = {.lex_state = 2},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 2},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 2},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 2},
  [27] = {.lex_state = 2},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 2},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 2},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 2},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 2},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 1},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 10},
  [70] = {.lex_state = 1},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 10},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 1},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 1},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 3},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 1},
  [106] = {.lex_state = 1},
  [107] = {.lex_state = 10},
  [108] = {.lex_state = 10},
  [109] = {.lex_state = 10},
  [110] = {.lex_state = 10},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 10},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 10},
  [115] = {.lex_state = 10},
  [116] = {.lex_state = 0},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 0},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 0},
  [139] = {.lex_state = 0},
  [140] = {.lex_state = 0},
  [141] = {.lex_state = 0},
  [142] = {.lex_state = 0},
  [143] = {.lex_state = 0},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 0},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 0},
  [150] = {.lex_state = 0},
  [151] = {.lex_state = 0},
  [152] = {.lex_state = 0},
  [153] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_tag_start] = ACTIONS(1),
    [sym_tag_end] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [sym_null] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym__string_escape_sequence] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_DOLLAR] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
  },
  [1] = {
    [sym_content] = STATE(147),
    [sym_markdown] = STATE(69),
    [sym_tag] = STATE(69),
    [sym_annotation] = STATE(69),
    [sym_interpolation] = STATE(69),
    [aux_sym_content_repeat1] = STATE(69),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_markdown_token1] = ACTIONS(5),
    [sym_tag_start] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_LBRACK,
    ACTIONS(23), 1,
      anon_sym_LBRACE,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(97), 1,
      sym_value,
    STATE(105), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    STATE(135), 1,
      sym_variable_sigil,
    ACTIONS(11), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(15), 2,
      sym_null,
      sym_number,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(73), 2,
      sym_boolean,
      sym_string,
    STATE(87), 2,
      sym_array,
      sym_hash,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
    STATE(90), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [73] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(121), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    STATE(153), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(12), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [130] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
    STATE(121), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    STATE(149), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(12), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [187] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(121), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    STATE(143), 1,
      sym__array_item_with_optional_comma,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(4), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [244] = 16,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(121), 1,
      sym_value,
    STATE(132), 1,
      sym__array_item_with_optional_comma,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(3), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [301] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(53), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(11), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [355] = 15,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(58), 1,
      sym_null,
    ACTIONS(64), 1,
      sym_number,
    ACTIONS(67), 1,
      anon_sym_DQUOTE,
    ACTIONS(70), 1,
      anon_sym_LBRACK,
    ACTIONS(73), 1,
      anon_sym_LBRACE,
    ACTIONS(79), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(61), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(76), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(8), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [409] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(81), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(10), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [463] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(8), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [517] = 15,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    STATE(34), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(8), 2,
      sym_function_parameters,
      aux_sym_function_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [571] = 15,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(90), 1,
      sym_null,
    ACTIONS(96), 1,
      sym_number,
    ACTIONS(99), 1,
      anon_sym_DQUOTE,
    ACTIONS(102), 1,
      anon_sym_LBRACK,
    ACTIONS(105), 1,
      anon_sym_RBRACK,
    ACTIONS(107), 1,
      anon_sym_LBRACE,
    STATE(133), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(93), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(110), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(12), 2,
      sym__array_item,
      aux_sym_array_repeat1,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [625] = 14,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      sym_identifier,
    STATE(50), 1,
      sym_function_parameter,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(49), 2,
      sym_value,
      sym_function_parameter_named,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [676] = 15,
    ACTIONS(115), 1,
      sym_identifier,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(95), 1,
      sym_attribute,
    STATE(120), 1,
      sym_tag_open,
    STATE(131), 1,
      sym__shorthand_sigil,
    STATE(135), 1,
      sym_variable_sigil,
    STATE(138), 1,
      sym_tag_interior,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(106), 2,
      sym_variable,
      sym_function,
    STATE(134), 2,
      sym_tag_self_closing,
      sym_tag_close,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [728] = 13,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(117), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [775] = 13,
    ACTIONS(15), 1,
      sym_null,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(121), 1,
      sym_number,
    ACTIONS(123), 1,
      anon_sym_DQUOTE,
    ACTIONS(125), 1,
      anon_sym_LBRACK,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    STATE(78), 1,
      sym_value,
    STATE(135), 1,
      sym_variable_sigil,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(73), 2,
      sym_boolean,
      sym_string,
    STATE(87), 2,
      sym_array,
      sym_hash,
    STATE(90), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [822] = 13,
    ACTIONS(29), 1,
      sym_identifier,
    ACTIONS(31), 1,
      sym_null,
    ACTIONS(35), 1,
      sym_number,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(39), 1,
      anon_sym_LBRACK,
    ACTIONS(43), 1,
      anon_sym_LBRACE,
    STATE(48), 1,
      sym_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(33), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(30), 2,
      sym_boolean,
      sym_string,
    STATE(33), 2,
      sym_array,
      sym_hash,
    STATE(38), 4,
      sym_primitive,
      sym_compound,
      sym_variable,
      sym_function,
  [869] = 3,
    STATE(18), 1,
      aux_sym__space,
    ACTIONS(131), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
    ACTIONS(129), 14,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      sym_identifier,
  [894] = 13,
    ACTIONS(117), 1,
      anon_sym_SLASH,
    ACTIONS(134), 1,
      sym_identifier,
    STATE(14), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(99), 1,
      aux_sym_interpolation_repeat1,
    STATE(120), 1,
      sym_tag_open,
    STATE(131), 1,
      sym__shorthand_sigil,
    STATE(136), 1,
      sym_tag_interior,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(43), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    STATE(134), 2,
      sym_tag_self_closing,
      sym_tag_close,
    ACTIONS(136), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [939] = 5,
    ACTIONS(140), 1,
      anon_sym_DOT,
    ACTIONS(144), 1,
      anon_sym_LBRACK,
    STATE(21), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(138), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(142), 9,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [967] = 5,
    ACTIONS(148), 1,
      anon_sym_DOT,
    ACTIONS(153), 1,
      anon_sym_LBRACK,
    STATE(21), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(146), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(151), 9,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [995] = 5,
    ACTIONS(140), 1,
      anon_sym_DOT,
    ACTIONS(144), 1,
      anon_sym_LBRACK,
    STATE(20), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(156), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(158), 9,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1023] = 2,
    ACTIONS(160), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(162), 11,
      anon_sym_DOT,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1043] = 2,
    ACTIONS(164), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(166), 11,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1063] = 2,
    ACTIONS(168), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(170), 11,
      anon_sym_DOT,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1083] = 2,
    ACTIONS(172), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(174), 11,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_COLON,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1103] = 2,
    ACTIONS(176), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(178), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1122] = 2,
    ACTIONS(180), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(182), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1141] = 2,
    ACTIONS(184), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(186), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1160] = 2,
    ACTIONS(188), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(190), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1179] = 2,
    ACTIONS(192), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(194), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1198] = 2,
    ACTIONS(196), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(198), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1217] = 2,
    ACTIONS(200), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(202), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1236] = 4,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(41), 2,
      sym_function_parameter_tail,
      aux_sym_function_parameters_repeat1,
    ACTIONS(204), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(206), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1259] = 2,
    ACTIONS(210), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(212), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1278] = 2,
    ACTIONS(214), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(216), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1297] = 4,
    ACTIONS(222), 1,
      anon_sym_COMMA,
    STATE(37), 2,
      sym_function_parameter_tail,
      aux_sym_function_parameters_repeat1,
    ACTIONS(218), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(220), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1320] = 2,
    ACTIONS(225), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(227), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1339] = 2,
    ACTIONS(210), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(212), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1358] = 2,
    ACTIONS(229), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(231), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1377] = 4,
    ACTIONS(208), 1,
      anon_sym_COMMA,
    STATE(37), 2,
      sym_function_parameter_tail,
      aux_sym_function_parameters_repeat1,
    ACTIONS(233), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(235), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1400] = 2,
    ACTIONS(237), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(239), 10,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1419] = 9,
    ACTIONS(241), 1,
      sym_identifier,
    ACTIONS(243), 1,
      sym_tag_end,
    STATE(51), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(45), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    ACTIONS(245), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1451] = 9,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(105), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(247), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1483] = 9,
    ACTIONS(249), 1,
      sym_identifier,
    ACTIONS(252), 1,
      sym_tag_end,
    STATE(58), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(254), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    STATE(45), 2,
      sym_attribute,
      aux_sym_annotation_repeat1,
    ACTIONS(257), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1515] = 9,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(105), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(260), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1547] = 9,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(105), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(262), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1579] = 2,
    ACTIONS(264), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(266), 8,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1596] = 2,
    ACTIONS(268), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(270), 8,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1613] = 2,
    ACTIONS(272), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(274), 8,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_COMMA,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
      anon_sym_RPAREN,
  [1630] = 9,
    ACTIONS(241), 1,
      sym_identifier,
    ACTIONS(276), 1,
      sym_tag_end,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(95), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1661] = 2,
    ACTIONS(278), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(280), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
  [1677] = 2,
    ACTIONS(278), 4,
      sym_null,
      anon_sym_true,
      anon_sym_false,
      sym_identifier,
    ACTIONS(280), 7,
      sym_number,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_DOLLAR,
      anon_sym_AT,
  [1693] = 4,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      anon_sym_LBRACK,
    STATE(55), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(138), 7,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1713] = 4,
    ACTIONS(286), 1,
      anon_sym_DOT,
    ACTIONS(289), 1,
      anon_sym_LBRACK,
    STATE(55), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(146), 7,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1733] = 4,
    ACTIONS(282), 1,
      anon_sym_DOT,
    ACTIONS(284), 1,
      anon_sym_LBRACK,
    STATE(54), 2,
      sym_variable_tail,
      aux_sym_variable_repeat1,
    ACTIONS(156), 7,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1753] = 8,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(105), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1781] = 8,
    ACTIONS(241), 1,
      sym_identifier,
    STATE(18), 1,
      aux_sym__space,
    STATE(79), 1,
      sym__attribute_full,
    STATE(84), 1,
      sym__attribute_shorthand,
    STATE(95), 1,
      sym_attribute,
    STATE(131), 1,
      sym__shorthand_sigil,
    ACTIONS(13), 2,
      anon_sym_DOT,
      anon_sym_POUND,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1809] = 7,
    ACTIONS(119), 1,
      sym_identifier,
    ACTIONS(292), 1,
      sym_tag_end,
    STATE(18), 1,
      aux_sym__space,
    STATE(135), 1,
      sym_variable_sigil,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(106), 2,
      sym_variable,
      sym_function,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1835] = 6,
    ACTIONS(119), 1,
      sym_identifier,
    STATE(18), 1,
      aux_sym__space,
    STATE(135), 1,
      sym_variable_sigil,
    ACTIONS(25), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(106), 2,
      sym_variable,
      sym_function,
    ACTIONS(27), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1858] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(294), 1,
      sym_identifier,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    STATE(67), 1,
      aux_sym_hash_repeat1,
    STATE(116), 1,
      sym__hash_item,
    STATE(122), 1,
      sym__hash_key_value,
    STATE(129), 1,
      sym_string,
    STATE(142), 1,
      sym__hash_item_with_optional_comma,
    STATE(144), 1,
      sym_hash_key,
  [1886] = 1,
    ACTIONS(160), 9,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LBRACK,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1898] = 1,
    ACTIONS(168), 9,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      anon_sym_LBRACK,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1910] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(294), 1,
      sym_identifier,
    ACTIONS(298), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_hash_repeat1,
    STATE(116), 1,
      sym__hash_item,
    STATE(122), 1,
      sym__hash_key_value,
    STATE(129), 1,
      sym_string,
    STATE(144), 1,
      sym_hash_key,
    STATE(150), 1,
      sym__hash_item_with_optional_comma,
  [1938] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(294), 1,
      sym_identifier,
    ACTIONS(300), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_hash_repeat1,
    STATE(116), 1,
      sym__hash_item,
    STATE(122), 1,
      sym__hash_key_value,
    STATE(129), 1,
      sym_string,
    STATE(144), 1,
      sym_hash_key,
    STATE(145), 1,
      sym__hash_item_with_optional_comma,
  [1966] = 6,
    ACTIONS(304), 1,
      anon_sym_EQ,
    ACTIONS(306), 1,
      anon_sym_LPAREN,
    STATE(2), 1,
      aux_sym__space,
    STATE(93), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(302), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(308), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [1988] = 9,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(294), 1,
      sym_identifier,
    ACTIONS(310), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_hash_repeat1,
    STATE(116), 1,
      sym__hash_item,
    STATE(122), 1,
      sym__hash_key_value,
    STATE(129), 1,
      sym_string,
    STATE(139), 1,
      sym__hash_item_with_optional_comma,
    STATE(144), 1,
      sym_hash_key,
  [2016] = 1,
    ACTIONS(237), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2027] = 4,
    ACTIONS(5), 1,
      aux_sym_markdown_token1,
    ACTIONS(7), 1,
      sym_tag_start,
    ACTIONS(312), 1,
      ts_builtin_sym_end,
    STATE(81), 5,
      sym_markdown,
      sym_tag,
      sym_annotation,
      sym_interpolation,
      aux_sym_content_repeat1,
  [2044] = 1,
    ACTIONS(229), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2055] = 1,
    ACTIONS(314), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2066] = 6,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(316), 1,
      sym_number,
    STATE(137), 1,
      sym_variable_sigil,
    STATE(151), 1,
      sym_variable_segment_value,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(123), 2,
      sym_string,
      sym_variable,
  [2087] = 1,
    ACTIONS(188), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2098] = 1,
    ACTIONS(184), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2109] = 5,
    ACTIONS(304), 1,
      anon_sym_EQ,
    STATE(2), 1,
      aux_sym__space,
    STATE(93), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(302), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(308), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2128] = 1,
    ACTIONS(172), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2139] = 1,
    ACTIONS(192), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2150] = 1,
    ACTIONS(318), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2161] = 1,
    ACTIONS(320), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2172] = 6,
    ACTIONS(37), 1,
      anon_sym_DQUOTE,
    ACTIONS(316), 1,
      sym_number,
    STATE(130), 1,
      sym_variable_segment_value,
    STATE(137), 1,
      sym_variable_sigil,
    ACTIONS(45), 2,
      anon_sym_DOLLAR,
      anon_sym_AT,
    STATE(123), 2,
      sym_string,
      sym_variable,
  [2193] = 4,
    ACTIONS(322), 1,
      ts_builtin_sym_end,
    ACTIONS(324), 1,
      aux_sym_markdown_token1,
    ACTIONS(327), 1,
      sym_tag_start,
    STATE(81), 5,
      sym_markdown,
      sym_tag,
      sym_annotation,
      sym_interpolation,
      aux_sym_content_repeat1,
  [2210] = 1,
    ACTIONS(164), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2221] = 8,
    ACTIONS(330), 1,
      sym_identifier,
    ACTIONS(333), 1,
      anon_sym_DQUOTE,
    ACTIONS(336), 1,
      anon_sym_RBRACE,
    STATE(83), 1,
      aux_sym_hash_repeat1,
    STATE(116), 1,
      sym__hash_item,
    STATE(129), 1,
      sym_string,
    STATE(144), 1,
      sym_hash_key,
    STATE(146), 1,
      sym__hash_key_value,
  [2246] = 1,
    ACTIONS(338), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2257] = 1,
    ACTIONS(180), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2268] = 1,
    ACTIONS(176), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2279] = 1,
    ACTIONS(200), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2290] = 1,
    ACTIONS(196), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2301] = 1,
    ACTIONS(210), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2312] = 1,
    ACTIONS(225), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2323] = 1,
    ACTIONS(210), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2334] = 1,
    ACTIONS(214), 8,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2345] = 4,
    STATE(47), 1,
      aux_sym__space,
    STATE(94), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(11), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(340), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2361] = 4,
    STATE(57), 1,
      aux_sym__space,
    STATE(94), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(342), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(344), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2377] = 1,
    ACTIONS(252), 7,
      sym_tag_end,
      anon_sym_DOT,
      anon_sym_POUND,
      sym_identifier,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2387] = 4,
    STATE(44), 1,
      aux_sym__space,
    STATE(94), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(260), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(347), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2403] = 4,
    STATE(46), 1,
      aux_sym__space,
    STATE(96), 1,
      aux_sym_tag_open_repeat1,
    ACTIONS(262), 2,
      sym_tag_end,
      anon_sym_SLASH,
    ACTIONS(349), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2419] = 4,
    ACTIONS(351), 1,
      sym_tag_end,
    STATE(60), 1,
      aux_sym__space,
    STATE(98), 1,
      aux_sym_interpolation_repeat1,
    ACTIONS(353), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2434] = 4,
    ACTIONS(356), 1,
      sym_tag_end,
    STATE(59), 1,
      aux_sym__space,
    STATE(98), 1,
      aux_sym_interpolation_repeat1,
    ACTIONS(358), 3,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2449] = 3,
    ACTIONS(360), 1,
      anon_sym_DQUOTE,
    ACTIONS(362), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(100), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2461] = 3,
    ACTIONS(365), 1,
      anon_sym_DQUOTE,
    ACTIONS(367), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(100), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2473] = 3,
    ACTIONS(369), 1,
      anon_sym_DQUOTE,
    ACTIONS(367), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(100), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2485] = 3,
    ACTIONS(371), 1,
      anon_sym_DQUOTE,
    ACTIONS(373), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(101), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2497] = 3,
    ACTIONS(375), 1,
      anon_sym_DQUOTE,
    ACTIONS(377), 2,
      sym__string_character,
      sym__string_escape_sequence,
    STATE(102), 2,
      sym__string_element,
      aux_sym_string_repeat1,
  [2509] = 1,
    ACTIONS(342), 5,
      sym_tag_end,
      anon_sym_SLASH,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2517] = 1,
    ACTIONS(351), 4,
      sym_tag_end,
      anon_sym_TAB,
      anon_sym_,
      anon_sym_LF,
  [2524] = 1,
    ACTIONS(379), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2530] = 1,
    ACTIONS(381), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2536] = 1,
    ACTIONS(383), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2542] = 1,
    ACTIONS(385), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2548] = 1,
    ACTIONS(387), 3,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
  [2554] = 1,
    ACTIONS(389), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2560] = 1,
    ACTIONS(387), 3,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
  [2566] = 1,
    ACTIONS(391), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2572] = 1,
    ACTIONS(393), 3,
      ts_builtin_sym_end,
      aux_sym_markdown_token1,
      sym_tag_start,
  [2578] = 1,
    ACTIONS(395), 3,
      anon_sym_DQUOTE,
      anon_sym_RBRACE,
      sym_identifier,
  [2584] = 1,
    ACTIONS(397), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2589] = 2,
    ACTIONS(399), 1,
      anon_sym_EQ,
    ACTIONS(401), 1,
      anon_sym_LPAREN,
  [2596] = 2,
    ACTIONS(403), 1,
      anon_sym_EQ,
    ACTIONS(405), 1,
      anon_sym_LPAREN,
  [2603] = 2,
    ACTIONS(407), 1,
      sym_tag_end,
    ACTIONS(409), 1,
      anon_sym_SLASH,
  [2610] = 2,
    ACTIONS(411), 1,
      anon_sym_RBRACK,
    ACTIONS(413), 1,
      anon_sym_COMMA,
  [2617] = 2,
    ACTIONS(415), 1,
      anon_sym_COMMA,
    ACTIONS(417), 1,
      anon_sym_RBRACE,
  [2624] = 1,
    ACTIONS(419), 1,
      anon_sym_RBRACK,
  [2628] = 1,
    ACTIONS(405), 1,
      anon_sym_LPAREN,
  [2632] = 1,
    ACTIONS(421), 1,
      sym_identifier,
  [2636] = 1,
    ACTIONS(423), 1,
      sym_tag_end,
  [2640] = 1,
    ACTIONS(425), 1,
      sym_identifier,
  [2644] = 1,
    ACTIONS(427), 1,
      sym_tag_end,
  [2648] = 1,
    ACTIONS(429), 1,
      anon_sym_COLON,
  [2652] = 1,
    ACTIONS(431), 1,
      anon_sym_RBRACK,
  [2656] = 1,
    ACTIONS(433), 1,
      sym_identifier,
  [2660] = 1,
    ACTIONS(41), 1,
      anon_sym_RBRACK,
  [2664] = 1,
    ACTIONS(435), 1,
      anon_sym_COMMA,
  [2668] = 1,
    ACTIONS(407), 1,
      sym_tag_end,
  [2672] = 1,
    ACTIONS(437), 1,
      sym_identifier,
  [2676] = 1,
    ACTIONS(439), 1,
      sym_tag_end,
  [2680] = 1,
    ACTIONS(441), 1,
      sym_identifier,
  [2684] = 1,
    ACTIONS(443), 1,
      sym_tag_end,
  [2688] = 1,
    ACTIONS(445), 1,
      anon_sym_RBRACE,
  [2692] = 1,
    ACTIONS(403), 1,
      anon_sym_EQ,
  [2696] = 1,
    ACTIONS(447), 1,
      sym_identifier,
  [2700] = 1,
    ACTIONS(449), 1,
      anon_sym_RBRACE,
  [2704] = 1,
    ACTIONS(47), 1,
      anon_sym_RBRACK,
  [2708] = 1,
    ACTIONS(451), 1,
      anon_sym_COLON,
  [2712] = 1,
    ACTIONS(453), 1,
      anon_sym_RBRACE,
  [2716] = 1,
    ACTIONS(455), 1,
      anon_sym_COMMA,
  [2720] = 1,
    ACTIONS(457), 1,
      ts_builtin_sym_end,
  [2724] = 1,
    ACTIONS(459), 1,
      sym_identifier,
  [2728] = 1,
    ACTIONS(461), 1,
      anon_sym_RBRACK,
  [2732] = 1,
    ACTIONS(463), 1,
      anon_sym_RBRACE,
  [2736] = 1,
    ACTIONS(465), 1,
      anon_sym_RBRACK,
  [2740] = 1,
    ACTIONS(401), 1,
      anon_sym_LPAREN,
  [2744] = 1,
    ACTIONS(467), 1,
      anon_sym_RBRACK,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 73,
  [SMALL_STATE(4)] = 130,
  [SMALL_STATE(5)] = 187,
  [SMALL_STATE(6)] = 244,
  [SMALL_STATE(7)] = 301,
  [SMALL_STATE(8)] = 355,
  [SMALL_STATE(9)] = 409,
  [SMALL_STATE(10)] = 463,
  [SMALL_STATE(11)] = 517,
  [SMALL_STATE(12)] = 571,
  [SMALL_STATE(13)] = 625,
  [SMALL_STATE(14)] = 676,
  [SMALL_STATE(15)] = 728,
  [SMALL_STATE(16)] = 775,
  [SMALL_STATE(17)] = 822,
  [SMALL_STATE(18)] = 869,
  [SMALL_STATE(19)] = 894,
  [SMALL_STATE(20)] = 939,
  [SMALL_STATE(21)] = 967,
  [SMALL_STATE(22)] = 995,
  [SMALL_STATE(23)] = 1023,
  [SMALL_STATE(24)] = 1043,
  [SMALL_STATE(25)] = 1063,
  [SMALL_STATE(26)] = 1083,
  [SMALL_STATE(27)] = 1103,
  [SMALL_STATE(28)] = 1122,
  [SMALL_STATE(29)] = 1141,
  [SMALL_STATE(30)] = 1160,
  [SMALL_STATE(31)] = 1179,
  [SMALL_STATE(32)] = 1198,
  [SMALL_STATE(33)] = 1217,
  [SMALL_STATE(34)] = 1236,
  [SMALL_STATE(35)] = 1259,
  [SMALL_STATE(36)] = 1278,
  [SMALL_STATE(37)] = 1297,
  [SMALL_STATE(38)] = 1320,
  [SMALL_STATE(39)] = 1339,
  [SMALL_STATE(40)] = 1358,
  [SMALL_STATE(41)] = 1377,
  [SMALL_STATE(42)] = 1400,
  [SMALL_STATE(43)] = 1419,
  [SMALL_STATE(44)] = 1451,
  [SMALL_STATE(45)] = 1483,
  [SMALL_STATE(46)] = 1515,
  [SMALL_STATE(47)] = 1547,
  [SMALL_STATE(48)] = 1579,
  [SMALL_STATE(49)] = 1596,
  [SMALL_STATE(50)] = 1613,
  [SMALL_STATE(51)] = 1630,
  [SMALL_STATE(52)] = 1661,
  [SMALL_STATE(53)] = 1677,
  [SMALL_STATE(54)] = 1693,
  [SMALL_STATE(55)] = 1713,
  [SMALL_STATE(56)] = 1733,
  [SMALL_STATE(57)] = 1753,
  [SMALL_STATE(58)] = 1781,
  [SMALL_STATE(59)] = 1809,
  [SMALL_STATE(60)] = 1835,
  [SMALL_STATE(61)] = 1858,
  [SMALL_STATE(62)] = 1886,
  [SMALL_STATE(63)] = 1898,
  [SMALL_STATE(64)] = 1910,
  [SMALL_STATE(65)] = 1938,
  [SMALL_STATE(66)] = 1966,
  [SMALL_STATE(67)] = 1988,
  [SMALL_STATE(68)] = 2016,
  [SMALL_STATE(69)] = 2027,
  [SMALL_STATE(70)] = 2044,
  [SMALL_STATE(71)] = 2055,
  [SMALL_STATE(72)] = 2066,
  [SMALL_STATE(73)] = 2087,
  [SMALL_STATE(74)] = 2098,
  [SMALL_STATE(75)] = 2109,
  [SMALL_STATE(76)] = 2128,
  [SMALL_STATE(77)] = 2139,
  [SMALL_STATE(78)] = 2150,
  [SMALL_STATE(79)] = 2161,
  [SMALL_STATE(80)] = 2172,
  [SMALL_STATE(81)] = 2193,
  [SMALL_STATE(82)] = 2210,
  [SMALL_STATE(83)] = 2221,
  [SMALL_STATE(84)] = 2246,
  [SMALL_STATE(85)] = 2257,
  [SMALL_STATE(86)] = 2268,
  [SMALL_STATE(87)] = 2279,
  [SMALL_STATE(88)] = 2290,
  [SMALL_STATE(89)] = 2301,
  [SMALL_STATE(90)] = 2312,
  [SMALL_STATE(91)] = 2323,
  [SMALL_STATE(92)] = 2334,
  [SMALL_STATE(93)] = 2345,
  [SMALL_STATE(94)] = 2361,
  [SMALL_STATE(95)] = 2377,
  [SMALL_STATE(96)] = 2387,
  [SMALL_STATE(97)] = 2403,
  [SMALL_STATE(98)] = 2419,
  [SMALL_STATE(99)] = 2434,
  [SMALL_STATE(100)] = 2449,
  [SMALL_STATE(101)] = 2461,
  [SMALL_STATE(102)] = 2473,
  [SMALL_STATE(103)] = 2485,
  [SMALL_STATE(104)] = 2497,
  [SMALL_STATE(105)] = 2509,
  [SMALL_STATE(106)] = 2517,
  [SMALL_STATE(107)] = 2524,
  [SMALL_STATE(108)] = 2530,
  [SMALL_STATE(109)] = 2536,
  [SMALL_STATE(110)] = 2542,
  [SMALL_STATE(111)] = 2548,
  [SMALL_STATE(112)] = 2554,
  [SMALL_STATE(113)] = 2560,
  [SMALL_STATE(114)] = 2566,
  [SMALL_STATE(115)] = 2572,
  [SMALL_STATE(116)] = 2578,
  [SMALL_STATE(117)] = 2584,
  [SMALL_STATE(118)] = 2589,
  [SMALL_STATE(119)] = 2596,
  [SMALL_STATE(120)] = 2603,
  [SMALL_STATE(121)] = 2610,
  [SMALL_STATE(122)] = 2617,
  [SMALL_STATE(123)] = 2624,
  [SMALL_STATE(124)] = 2628,
  [SMALL_STATE(125)] = 2632,
  [SMALL_STATE(126)] = 2636,
  [SMALL_STATE(127)] = 2640,
  [SMALL_STATE(128)] = 2644,
  [SMALL_STATE(129)] = 2648,
  [SMALL_STATE(130)] = 2652,
  [SMALL_STATE(131)] = 2656,
  [SMALL_STATE(132)] = 2660,
  [SMALL_STATE(133)] = 2664,
  [SMALL_STATE(134)] = 2668,
  [SMALL_STATE(135)] = 2672,
  [SMALL_STATE(136)] = 2676,
  [SMALL_STATE(137)] = 2680,
  [SMALL_STATE(138)] = 2684,
  [SMALL_STATE(139)] = 2688,
  [SMALL_STATE(140)] = 2692,
  [SMALL_STATE(141)] = 2696,
  [SMALL_STATE(142)] = 2700,
  [SMALL_STATE(143)] = 2704,
  [SMALL_STATE(144)] = 2708,
  [SMALL_STATE(145)] = 2712,
  [SMALL_STATE(146)] = 2716,
  [SMALL_STATE(147)] = 2720,
  [SMALL_STATE(148)] = 2724,
  [SMALL_STATE(149)] = 2728,
  [SMALL_STATE(150)] = 2732,
  [SMALL_STATE(151)] = 2736,
  [SMALL_STATE(152)] = 2740,
  [SMALL_STATE(153)] = 2744,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(119),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 2, .production_id = 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(74),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(125),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(152),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(30),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(29),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(30),
  [67] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(103),
  [70] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(5),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(65),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2), SHIFT_REPEAT(125),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_repeat1, 2),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(152),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(30),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(29),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(30),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(103),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(5),
  [105] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(65),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2), SHIFT_REPEAT(125),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(118),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(66),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(141),
  [119] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__space, 2),
  [131] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__space, 2), SHIFT_REPEAT(18),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2),
  [148] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(148),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2),
  [153] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(72),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 2),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_tail, 3),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_tail, 3),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable_tail, 2),
  [170] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_tail, 2),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [176] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 4),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 4),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 4, .production_id = 7),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 4, .production_id = 7),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 4),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 4),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_compound, 1),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_compound, 1),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameters, 1),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 1),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [210] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 3, .production_id = 5),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 3, .production_id = 5),
  [214] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_function_parameters_repeat1, 2),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_parameters_repeat1, 2),
  [222] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_parameters_repeat1, 2), SHIFT_REPEAT(13),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hash, 2),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash, 2),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameters, 2),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameters, 2),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function, 3),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(140),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(115),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 5, .production_id = 1),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2), SHIFT_REPEAT(140),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2), SHIFT_REPEAT(131),
  [257] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_annotation_repeat1, 2), SHIFT_REPEAT(58),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 4, .production_id = 1),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 3, .production_id = 1),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameter_named, 3),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameter_named, 3),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameter, 1),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameter, 1),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_parameter_tail, 2),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_parameter_tail, 2),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [278] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__array_item, 2),
  [280] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_item, 2),
  [282] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(80),
  [286] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(127),
  [289] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_variable_repeat1, 2), SHIFT_REPEAT(80),
  [292] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [302] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_open, 1, .production_id = 1),
  [304] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [306] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [310] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__attribute_shorthand, 2),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [318] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__attribute_full, 3, .production_id = 4),
  [320] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, .production_id = 2),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2),
  [324] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(107),
  [327] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_content_repeat1, 2), SHIFT_REPEAT(19),
  [330] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, .production_id = 6), SHIFT_REPEAT(129),
  [333] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, .production_id = 6), SHIFT_REPEAT(103),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 2, .production_id = 6),
  [338] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1),
  [340] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [342] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_open_repeat1, 2),
  [344] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_open_repeat1, 2), SHIFT_REPEAT(57),
  [347] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [349] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [351] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2),
  [353] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_interpolation_repeat1, 2), SHIFT_REPEAT(60),
  [356] = {.entry = {.count = 1, .reusable = false}}, SHIFT(114),
  [358] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [360] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [362] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(100),
  [365] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [369] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [371] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [375] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [377] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [379] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_markdown, 1),
  [381] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3),
  [383] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 4),
  [385] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 4),
  [387] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hash_item, 2, .production_id = 2),
  [389] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 4),
  [391] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3),
  [393] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_annotation, 3),
  [395] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hash_repeat1, 1, .production_id = 2),
  [397] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hash_key_value, 3, .production_id = 4),
  [399] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [401] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [403] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [407] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_interior, 1),
  [409] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [411] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__array_item_with_optional_comma, 1),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [417] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__hash_item_with_optional_comma, 1, .production_id = 2),
  [419] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_segment_value, 1),
  [421] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable_sigil, 1),
  [423] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_self_closing, 2),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [427] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_close, 2, .production_id = 3),
  [429] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hash_key, 1),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [435] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [439] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [441] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [443] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [445] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [447] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [449] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [451] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [453] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [455] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [457] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [459] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [461] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [463] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [465] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [467] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_markdoc(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
